package B1;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author roxph
 */
import B1.*;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.nio.file.Paths;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHParameterSpec;
import javax.crypto.spec.SecretKeySpec;
public class frm_Bob extends javax.swing.JFrame {

    /**
     * Creates new form frm_Alice
     */
    public frm_Bob() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        txt_bob_key = new javax.swing.JTextField();
        txt_alice_key = new javax.swing.JTextField();
        txt_encrypt_shared_secret = new javax.swing.JTextField();
        txt_shared_secret = new javax.swing.JTextField();
        btn_bob_key_generate = new javax.swing.JButton();
        btn_alice_key_display = new javax.swing.JButton();
        btn_enrcypt_secret_key = new javax.swing.JButton();
        btn_encrypt_decrypt = new javax.swing.JButton();
        btn_make_secret_key = new javax.swing.JButton();

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_bob_key_generate.setText("GEN BOB KEY");
        btn_bob_key_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bob_key_generateActionPerformed(evt);
            }
        });

        btn_alice_key_display.setText("SHOW ALICE KEY");
        btn_alice_key_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alice_key_displayActionPerformed(evt);
            }
        });

        btn_enrcypt_secret_key.setText("ENCRYPT SECRET");
        btn_enrcypt_secret_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enrcypt_secret_keyActionPerformed(evt);
            }
        });

        btn_encrypt_decrypt.setText("OPEN ENCYPT DECRYPT");
        btn_encrypt_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encrypt_decryptActionPerformed(evt);
            }
        });

        btn_make_secret_key.setText("MAKE SECRET");
        btn_make_secret_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_make_secret_keyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bob_key, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alice_key, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_encrypt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_enrcypt_secret_key, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_alice_key_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_make_secret_key, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bob_key_generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btn_encrypt_decrypt)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bob_key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bob_key_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alice_key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alice_key_display, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_make_secret_key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_encrypt_shared_secret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enrcypt_secret_key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_encrypt_decrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bob_key_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bob_key_generateActionPerformed
        // TODO add your handling code here:
        try {
            boolean read = false;
            java.nio.file.Path dirPath = Paths.get("src/week_04");

            // Create the directory if it doesn't exist
            if (!java.nio.file.Files.exists(dirPath)) {
                java.nio.file.Files.createDirectories(dirPath);
            }

            // Wait until the file is readable
            while (!read) {
                try (FileInputStream fis = new FileInputStream(dirPath.resolve("A.pub").toFile())) {
                    read = true;
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }

            // Read Alice's public key from the file
            byte[] alicePubKeyEnc;
            try (FileInputStream fis = new FileInputStream(dirPath.resolve("A.pub").toFile())) {
                alicePubKeyEnc = new byte[fis.available()];
                fis.read(alicePubKeyEnc);
            }

            // Generate Bob's key pair using Alice's public key
            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(alicePubKeyEnc);
            alicePubKey = bobKeyFac.generatePublic(x509KeySpec);

            // Initialize Bob's key pair generator with DH parameters from Alice's public key
            DHParameterSpec dhParamSpec = ((DHPublicKey) alicePubKey).getParams();
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize(dhParamSpec);
            KeyPair bobKpair = bobKpairGen.generateKeyPair();

            // Initialize the KeyAgreement instance with Bob's private key
            bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());

            // Encode and save Bob's public key to a file
            byte[] bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            try (FileOutputStream fos = new FileOutputStream(dirPath.resolve("B.pub").toFile())) {
                fos.write(bobPubKeyEnc);
            }

            // Display Bob's public key in Base64 format
            txt_bob_key.setText(java.util.Base64.getEncoder().encodeToString(bobPubKeyEnc));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_bob_key_generateActionPerformed

    private void btn_alice_key_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alice_key_displayActionPerformed
        // TODO add your handling code here:
          try {
            byte[] bkeyp;
            // Read Alice's public key from the file
            try (FileInputStream fis = new FileInputStream(Paths.get("src/week_04/A.pub").toFile())) {
                bkeyp = new byte[fis.available()];
                fis.read(bkeyp);
            }

            // Display the public key in the text field
            txt_alice_key.setText(java.util.Base64.getEncoder().encodeToString(bkeyp));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_alice_key_displayActionPerformed

    private void btn_make_secret_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_make_secret_keyActionPerformed
        // TODO add your handling code here:
        try {
            // Complete the key agreement phase with Alice's public key
            bobKeyAgree.doPhase(alicePubKey, true);

            // Generate the shared secret
            byte[] bobSharedSecret = bobKeyAgree.generateSecret();

            // Display the shared secret in hexadecimal format
            txt_shared_secret.setText(CryptoUtil.toHexString(bobSharedSecret));
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btn_make_secret_keyActionPerformed

    private void btn_enrcypt_secret_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enrcypt_secret_keyActionPerformed
        // TODO add your handling code here:
        try {
            // Complete the key agreement phase with Alice's public key
            bobKeyAgree.doPhase(alicePubKey, true);

            // Generate the shared secret
            byte[] sharedSecret = bobKeyAgree.generateSecret();

            // Display the shared secret in hexadecimal format
            txt_encrypt_shared_secret.setText(CryptoUtil.toHexString(sharedSecret));

            // Generate a DES key from the shared secret using SHA-256
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
            byte[] desKeyBytes = Arrays.copyOf(sha256.digest(sharedSecret), 8);
            SecretKeySpec desKeySpec = new SecretKeySpec(desKeyBytes, "DES");

            // Display the DES key in Base64 format
            txt_encrypt_shared_secret.setText(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));

            // Save the DES key to a file
            String fileName = "src/week_04/B.txt";
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {
                bw.write(Base64.getEncoder().encodeToString(desKeySpec.getEncoded()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_enrcypt_secret_keyActionPerformed

    private void btn_encrypt_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encrypt_decryptActionPerformed
        // TODO add your handling code here:
        frm_DESCS des = new frm_DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btn_encrypt_decryptActionPerformed
    
    // Generated Code
    private KeyAgreement bobKeyAgree;
    private PublicKey alicePubKey;
    private SecretKey bobDesKey;
    private Cipher bobCipher;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Bob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alice_key_display;
    private javax.swing.JButton btn_bob_key_generate;
    private javax.swing.JButton btn_encrypt_decrypt;
    private javax.swing.JButton btn_enrcypt_secret_key;
    private javax.swing.JButton btn_make_secret_key;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField txt_alice_key;
    private javax.swing.JTextField txt_bob_key;
    private javax.swing.JTextField txt_encrypt_shared_secret;
    private javax.swing.JTextField txt_shared_secret;
    // End of variables declaration//GEN-END:variables
}
